### ISSUE TITLE
Feature - connect missing family members

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/refugees-welcome-croatia-web#10]
Invent way to allow reporting of missing family members and connecting them.

**Comment by schlos** [comment]
brainstorming:
http://google.org/personfinder/global/responders.html

API:
https://github.com/google/personfinder/wiki/DataAPI

Github:
https://github.com/google/personfinder (Python)

**Comment by bobrock** [comment]
ja bih definitivno vido da li bi se moglo dogovoriti sa googlom da digne servis kod sebe pa da to bude globalno za cijelu krizu i da svi NGOovi iz regije (sa trase) dijele informacije...

**Comment by schlos** [comment]
Vec je netko u vezi ovoga zapoceo diskusiju na mailing listi za personfinder:

https://groups.google.com/forum/#!topic/personfinder/pSzdSgLt5hg

Odgovor:
"Due to the potential for violence against those displaced, Google will not be launching a Person Finder instance for the refugee crisis at this time."

**Comment by schlos** [comment]
cc @mzadravec

**Comment by schlos** [comment]
Sahana ima open source sustav za missing persons

http://sahanafoundation.org/products/vesuvius/

**Comment by schlos** [comment]
Vesuvius will be deployed at:
http://find.welcome.cms.hr

**Comment by schlos** [comment]
Other example of this person find app:
https://migrationaid.com/

**Comment by schlos** [comment]
Close as not needed at moment, already instance is already deployed.
